spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lib
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: off
